### ISSUE TITLE
Coerce, Schema fails when a column has type Vector{Missing}

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJScientificTypes.jl#37]
see issue https://github.com/alan-turing-institute/MLJ.jl/issues/549

**Comment by tlienart** [comment]
Thanks Sam, I'll look  into this

**Comment by ablaom** [comment]
I think this is now resolved; see  https://github.com/alan-turing-institute/MLJ.jl/issues/549
